### ISSUE TITLE
Background song doesn't start again

### ISSUE THREAD

**Issue by ghost** [natogourmet/javascript30#1]
In the main application's view after press on **click me to start** button when the background music comes to the end, It doesn't start again. I loved that song so could you extends or repeat it infinitly?

**Comment by natogourmet** [comment]
Hey! Nice to meet someone 'round here who likes FF too! Sure i will loop it just 4 u, hope you check it later on.

Sorry for the late reply, didnt even know 'bout this feature in GitHub

**Comment by ghost** [comment]
thanks dude c:
